services :
    cbfapi:
        image: rapha1010/cbfapi
        container_name: cbfapi
        restart: always
        ports:
            - 8081:8081
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./rabbitmqData:/var/lib/rabbitmq
        environment:
                - RABBITMQ_DEFAULT_USER=admin
                - RABBITMQ_DEFAULT_PASS=123456
    
